### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by arbazkiraak** [hahwul/a2sv#13]
Hello , 

I Like your Project Which Scans For SSL Vulnerabilties,

Hope you Won't Mind if i Ask for a Features Which Allow the Users to Give List of URL's to be Scanned ! 

Thanks!

**Comment by hahwul** [comment]
Hello bro.
I think the same. I will make a plan.
thank you!

**Comment by hahwul** [comment]
@arbazhussain149 
update to a2sv v1.4.6 !

`#> a2sv -f ./list.txt`
