### ISSUE TITLE
Save to Result

### ISSUE THREAD

**Issue by LAzyFrAAnk** [hahwul/a2sv#22]
Hi....

Scan result possible save to file, like html, txt...etc??

Or just ONLY a2sv -t xxxxxxx >> file location??

**Comment by hahwul** [comment]
Hi bro. 
Does not support current save function.
but i have plan for this idea. I'll develop it as soon as possible.
Thank you.

**Comment by hahwul** [comment]
@LAzyFrAAnk 
Hi
I have completed development of the "save a file" function.
please update a2sv and use the this function easily.

update a2sv
`#> a2sv -u `
or clone a2v after delete old a2sv
`git clone https://github.com/hahwul/a2sv`

and..  use the file save function

`#> a2sv.py -t [target_site] -o /etc/report_dir/a_taget.txt`
