### ISSUE TITLE
General Question

### ISSUE THREAD

**Issue by MeanMachine123** [hahwul/a2sv#23]
Which command Should I use after found a Vulnerability....??? I found different Vulnerabilities 👍  :)

**Comment by hahwul** [comment]
Thank you for question.

A2SV Scanner is ssl vulnerability scanner. Does not support current attack function.(e.g getting system, show encryption text ... )

Try to find the Attack code for the vulnerability found. It is also a good idea to use Metasploit :)
Um.. I have a question. What is "different vulnerabilities" you said?

Kind regards.
