### ISSUE TITLE
Bug in Termux

### ISSUE THREAD

**Issue by Stainle2S** [hahwul/a2sv#32]
$ python a2sv.py -h
  File "a2sv.py", line 128
    print ""
           ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("")?

Please, help me)

**Comment by binarioGH** [comment]
(i just speak a little bit of english) 
to use "print()", you must put what you want to print between parentheses

**Comment by hahwul** [comment]
Fixed this bug.
Please update a2sv
[ Update command ]
```
#> a2sv -u 

or 

#> cd a2sv
#> git pull
```

[ Change log ]  
```
print "" => " "
```
[ Code ]
```
127 
128     print " "
129     # SSL Check Logic --------------------------- 
```
Thank you for sending issues and solutions.

**Comment by ringawy** [comment]
same problem i have latest update and try above trick don't work 

python a2sv.py -u
  File "a2sv.py", line 128
    print " "
            ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(" ")?
