### ISSUE TITLE
Install script puts improper characters /usr/bin launch script

### ISSUE THREAD

**Issue by anthaeus** [hahwul/a2sv#7]
after using install.sh the script puts
# !/usr/bin/python\npython <launch_path>/a2sva2sv.py

in my case it was 
# !/usr/bin/python\npython /root/a2sva2sv.py

I think it should be
# !/usr/bin/python

python /root/a2sv/a2sv.py

**Comment by anthaeus** [comment]
the error is in the second-to-last line where ' characters are used incorrectly

**Comment by hahwul** [comment]
Thank you for good idea.
I modify the "install.sh" script   (https://github.com/hahwul/a2sv/commit/8a24ba818b8dcf966c65171a0548695b9da83145)
- remove "\n" char
- add 'enter" char
- change install path data
    before: python '$MYPWD'a2sv.py' >> /usr/bin/a2sv 
    after : python '$MYPWD'/a2sv.py' >> /usr/bin/a2sv

## Run log

   ┎ [ 01:10:51 : root ] [ /a2sv ] 
 HaHwul #> ./install.sh 
Install a2sv
 -> install python package
 -> pip:argparse
Requirement already satisfied (use --upgrade to upgrade): argparse in /usr/lib/python2.7
Cleaning up...
 -> pip:netaddr
Requirement already satisfied (use --upgrade to upgrade): netaddr in /usr/local/lib/python2.7/dist-packages
Cleaning up...
 -> install openssl(apt)
패키지 목록을 읽는 중입니다... 완료
의존성 트리를 만드는 중입니다  
상태 정보를 읽는 중입니다... 완료
openssl 패키지는 이미 최신 버전입니다.
0개 업그레이드, 0개 새로 설치, 0개 제거 및 0개 업그레이드 안 함.
 -> set command
Finish. run a a2sv

   ┎ [ 01:10:55 : root ] [ /a2sv ] 
 HaHwul #> cat /usr/bin/a2sv 
#/usr/bin/python
python /a2sv/a2sv.py
